---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: restart monitor
  service: name=monitor state=restarted

- name: restart osd
  service: name=osd state=restarted
